from collections.abc import Mapping
from typing import ClassVar, Protocol

from zeni.types import Payment, StandardColumns


class Bank(Protocol):
    class Columns: ...

    class Types: ...

    class Categories: ...

    column_map: ClassVar[Mapping[Columns, StandardColumns]]
    type_map: ClassVar[Mapping[Types, Payment]] = ...
    category_map: ClassVar[Mapping[Categories, Payment]] = ...
